[platformio]
default_envs = esp32dev

[env]
platform = espressif32
board = esp32dev
framework = espidf
monitor_speed = 115200
upload_speed = 115200

[env:esp32dev]
upload_port = COM5
monitor_port = COM5
build_flags =
  -D EXCELLENCE_NODE_ID=\"gateway_01\"
  -D EXCELLENCE_NODE_ROLE=EXCELLENCE_ROLE_GATEWAY

[env:relay_01]
upload_port = COM11
monitor_port = COM11
build_flags =
  -D EXCELLENCE_NODE_ID=\"relay_01\"
  -D EXCELLENCE_NODE_ROLE=EXCELLENCE_ROLE_RELAY

[env:relay_02]
upload_port = COM12
monitor_port = COM12
build_flags =
  -D EXCELLENCE_NODE_ID=\"relay_02\"
  -D EXCELLENCE_NODE_ROLE=EXCELLENCE_ROLE_RELAY

[env:actuator_01]
upload_port = COM12
monitor_port = COM12
build_flags =
  -D EXCELLENCE_NODE_ID=\"actuator_01\"
  -D EXCELLENCE_NODE_ROLE=EXCELLENCE_ROLE_ACTUATOR
