#ifndef EXCELLENCE_NODE_IDENTITY_H
#define EXCELLENCE_NODE_IDENTITY_H

#define EXCELLENCE_ROLE_GATEWAY 1
#define EXCELLENCE_ROLE_RELAY 2
#define EXCELLENCE_ROLE_SENSOR 3
#define EXCELLENCE_ROLE_ACTUATOR 4

#ifndef EXCELLENCE_NODE_ID
#define EXCELLENCE_NODE_ID "gateway_01"
#endif

#ifndef EXCELLENCE_NODE_ROLE
#define EXCELLENCE_NODE_ROLE EXCELLENCE_ROLE_GATEWAY
#endif

#if EXCELLENCE_NODE_ROLE != EXCELLENCE_ROLE_GATEWAY && \
    EXCELLENCE_NODE_ROLE != EXCELLENCE_ROLE_RELAY &&   \
    EXCELLENCE_NODE_ROLE != EXCELLENCE_ROLE_SENSOR &&  \
    EXCELLENCE_NODE_ROLE != EXCELLENCE_ROLE_ACTUATOR
#error "Invalid EXCELLENCE_NODE_ROLE. Use EXCELLENCE_ROLE_GATEWAY, EXCELLENCE_ROLE_RELAY, EXCELLENCE_ROLE_SENSOR, or EXCELLENCE_ROLE_ACTUATOR."
#endif

typedef enum {
  EXCELLENCE_NODE_ROLE_GATEWAY = EXCELLENCE_ROLE_GATEWAY,
  EXCELLENCE_NODE_ROLE_RELAY = EXCELLENCE_ROLE_RELAY,
  EXCELLENCE_NODE_ROLE_SENSOR = EXCELLENCE_ROLE_SENSOR,
  EXCELLENCE_NODE_ROLE_ACTUATOR = EXCELLENCE_ROLE_ACTUATOR,
} excellence_node_role_t;

typedef struct {
  const char *node_id;
  excellence_node_role_t role;
} excellence_node_identity_t;

const excellence_node_identity_t *excellence_node_identity_get(void);
const char *excellence_node_role_to_string(excellence_node_role_t role);

#endif
